solana-indexer:
  resources:
    jvm:
      xmx_megabytes: 4096
      max_direct_memory_megabytes: 1524

solana-api:
  replicas: 3
  resources:
    jvm:
      xmx_megabytes: 1024
      max_direct_memory_megabytes: 512