# Request block by number.

POST https://api.mainnet-beta.solana.com
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "getBlock",
  "params": [
    133285078,
    {
      "encoding": "json",
      "transactionDetails": "full",
      "rewards": false
    }
  ]
}